USE adlister_db;

INSERT INTO users (username, email, password)
VALUES ('admin', 'admin@admin.com', 'password');

INSERT INTO categories (title) VALUE ('test');

INSERT INTO tags (category_id, title) VALUES (1, 'other');

INSERT INTO ads (user_id, tag_id, title, description, posted_date)
VALUES (1, 1, 'Holy Grail', 'Decorated cup with historical significance', '2019-10-20'),
       (1, 1, 'The Kracken', 'Looking for a loving home', '2019-10-20'),
       (1, 1, 'The Moon', 'Taking any offer. No deliveries', '2019-10-20'),
       (1, 1, 'Not a flamethrower', 'I promise it is not a flamethrower', '2019-10-20'),
       (1, 1, 'Schrodinger''s Cat', 'Live cat will be shipped. Should be considered both alive and dead until package is received.', '2019-10-20'),
       (1, 1, 'Hitman', 'Really good at hitting baseballs.', '2019-10-20'),
       (1, 1, 'Uranium-238', '10 grams of enriched uranium-238. If delivery takes longer than 4.5 billion years, expect 5 grams', '2019-10-20'),
       (1, 1, 'Police Call Box', 'Old style, blue police phone booth. Surprisingly roomy on the inside.', '2019-10-20'),
       (1, 1, '2013 Toyota Tacoma', 'Registered to Brance Alexander. If interested contact Mitchell Arnold.', '2019-10-20'),
       (1, 1, 'Horse', 'It''s literally just a horse.', '2019-10-20'),
       (1, 1, 'Black Lotus', 'The perfect card for any MTG player that values winning more than friendship or their bank account.', '2019-10-20'),
       (1, 1, 'Location of Elvis Presley', 'GPS coordinates in exchange for cash.', '2019-10-20'),
       (1, 1, 'Duck', 'Perfect partner for coding.', '2019-10-20'),
       (1, 1, 'AyePhone', 'A pirated version of Apple''s smartphone.', '2019-10-20'),
       (1, 1, 'Beanie Babies', 'The 90''s promised that these would be worth money by now', '2019-10-20'),
       (1, 1, 'Baker needed', 'My son''s birthday is coming up and I want a special cake baked for him. I need someone who can bake a file into a cake because my son is a tool collector. Any flavor of cake and icing is fine. Decorations would be nice but are not required. Deliver to Texas State Penitentiary.', '2019-10-20'),
       (1, 1, 'Yes man needed', 'I need someone to follow me around and agree with everything I say. Pay is minimal and work conditions are demeaning.', '2019-10-20'),
       (1, 1, 'Batman needs city to protect', 'Don''t worry about what happened to Gotham. It will be better this time.', '2019-10-20'),
       (1, 1, 'Found dog', 'Looking for the owner of a dog found on the north side of San Antonio. Cannot tell the breed but he''s about 6.5 feet long and around 600 pounds. Seems to be fond of salmon and sleeping during winter.', '2019-10-20'),
       (1, 1, 'Compliments', 'You are a nice person.', '2019-10-20');
       INSERT INTO categories (title)
       VALUES ('Community'),
       ('Services'),
       ('Housing'),
       ('For Sale'),
       ('Jobs');

USE adlister_db;
       INSERT INTO tags (category_id, title)
       VALUES ('1', 'Activities'),
       ('1','Artists'),
       ('1', 'Childcare'),
       ('1', 'Classes'),
       ('1', 'Events'),
       ('1', 'General'),
       ('1', 'Groups'),
       ('1', 'Local News'),
       ('1', 'Lost and Found'),
       ('1', 'Missed Connections'),
       ('1', 'Musicians'),
       ('1', 'Pets'),
       ('1', 'Politics'),
       ('1', 'Rants and Raves'),
       ('1', 'Rideshare'),
       ('1', 'Volunteers'),
        ('2','Automotive'),
        ('2', 'Beauty'),
       ('2', 'Cell/Mobile'),
       ('2', 'Computer'),
       ('2', 'Creative'),
       ('2', 'Cycle'),
       ('2', 'Event'),
       ('2', 'Farm and Garden'),
       ('2', 'Financial'),
       ('2', 'Household'),
       ('2', 'Labor/Moving'),
       ('2', 'Legal'),
       ('2', 'Lessons'),
       ('2', 'Marine'),
       ('2', 'Pet'),
       ('2', 'Real Estate'),
       ('2', 'Skilled  Trade'),
       ('2', 'Small Business Ads'),
       ('2', 'Travel/Vacation'),
       ('2', 'Lessons'),
       ('2', 'Marine'),
       ('2', 'Writing/Education/Training'),
         ('3','Apartments/Housing'),
        ('3', 'House Swap'),
       ('3', 'Housing Wanted'),
       ('3', 'Office/ Commercial'),
       ('3', 'Parking/Storage'),
       ('3', 'Real Estate For Sale'),
       ('3', 'Shared Rooms'),
       ('3', 'Sublets/ Temporary'),
       ('3', 'Vacation Rentals'),
          ('4', 'Antiques'),
       ('4', 'Appliances'),
       ('4', 'Arts and Crafts'),
       ('4', 'ATV/UTV/SNO'),
       ('4', 'Auto Parts'),
       ('4', 'Aviation'),
       ('4', 'Babies and Kids'),
         ('4','Barter'),
        ('4', 'Health and Beauty'),
       ('4', 'Bike Parts'),
       ('4', 'Bikes'),
       ('4', 'Boat Parts'),
       ('4', 'Boats'),
       ('4', 'Books'),
       ('4', 'Business'),
       ('4', 'Cars and Trucks'),
        ('4', 'Cds/Dvds/Vhs'),
       ('4', 'Clothes'),
       ('4', 'Collectibles'),
       ('4', 'Computer Parts'),
       ('4', 'Computers'),
       ('4', 'Electronics'),
         ('4', 'Farming and Gardening'),
       ('4', 'Free'),
       ('4', 'Furniture'),
       ('4', 'Garage Sale'),
       ('4', 'General'),
       ('4', 'Heavy Equipment'),
        ('4', 'Household'),
       ('4', 'Jewelry'),
       ('4', 'Materials'),
       ('4', 'Motorcycle Parts'),
       ('4', 'Motorcycles'),
       ('4', 'Music Instruments'),
       ('4', 'Photo and Video'),
            ('4', 'RVs/Camping'),
       ('4', 'Sporting'),
       ('4', 'Tickets'),
        ('4', 'Tools'),
       ('4', 'Toys and Games'),
       ('4', 'Trailers'),
       ('4', 'Video Games'),
       ('4', 'Wanted'),
       ('4', 'Wheels and Tires'),
              ('5', 'Accounting/Finance'),
       ('5', 'Admin/Office'),
       ('5', 'Architect/ Engineering'),
       ('5', 'Art/Media/Design'),
       ('5', 'Biotech/Science'),
       ('5', 'Business Management'),
       ('5', 'Customer Service'),
         ('5','Education'),
        ('5', 'Miscellaneous'),
       ('5', 'Food/Beverage/Hospitality'),
       ('5', 'General Labor'),
       ('5', 'Government'),
       ('5', 'Human Resources'),
       ('5', 'Legal/Paralegal'),
       ('5', 'Manufacturing'),
       ('5', 'Marketing/Public Relations'),
        ('5', 'Medical/Health'),
       ('5', 'Nonprofit'),
       ('5', 'Real Estate'),
       ('5', 'Retail/Wholesale'),
       ('5', 'Sales'),
       ('5', 'Salon/Spa/Fitness'),
         ('5', 'Security'),
       ('5', 'Skilled Trade/Craft'),
       ('5', 'Sotware/QA/Dba'),
       ('5', 'Systems/Network'),
       ('5', 'Technical Support'),
       ('5', 'Transport'),
        ('5', 'TV/Film/Video'),
       ('5', 'Web/Info Design'),
       ('5', 'Writing/Editing');


